// <auto-generated />
using System;
using Agreed.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agreed.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210326201939_AddedUserTables")]
    partial class AddedUserTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Agreed.Core.Entities.Order", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AmountTobeBilled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoutiqueNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CargoDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("float");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PackageNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Piece")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderNumber = "123",
                            AmountTobeBilled = 150m,
                            Barcode = "0000000000001998",
                            BillingAddress = "İstanbul",
                            BoutiqueNumber = "123456",
                            Brand = "HAC",
                            CargoCode = "123456",
                            CargoCompany = "HAC CARGO",
                            CargoDeliveryDate = new DateTime(2021, 3, 26, 23, 19, 37, 899, DateTimeKind.Local).AddTicks(424),
                            CommissionRate = 10.5,
                            DeliveryAddress = "Denizli",
                            DiscountAmount = 10m,
                            Email = "anil@hacyazilim.com.tr",
                            OrderDate = new DateTime(2021, 3, 19, 23, 19, 37, 902, DateTimeKind.Local).AddTicks(2565),
                            OrderStatus = 0,
                            PackageNumber = "123",
                            Piece = 1,
                            ProductName = "HAC",
                            Receiver = "",
                            SalesAmount = 150m,
                            StockCode = "aaaa",
                            UnitPrice = 150m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
